services:
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.0-17900959199
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - default
    restart: unless-stopped

volumes:
  grafana-storage:
    driver: local
